// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Link struct {
	ID          string       `json:"id"`
	OriginalUrl string       `json:"original_url"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
